cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('detail/', views.cartDetail, name='cartDetail'),
    path('add/', views.cartAdd, name='cartAdd'),
    path('delete/', views.cartDelete, name='cartDelete'),
    path('update/', views.cartUpdate, name='cartUpdate'),
]

payments/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'payments'

urlpatterns = [
    path('', views.payments, name='payment'),
    path('creditCardPayment/', views.creditCardPayment, name='creditCardPayment'),
    path('paymentDone/', views.paymentDone, name='paymentDone'),
]

weddingwizard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from django.contrib import admin
from django.urls import path, include

# Added by me

from core.views import index, services

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('cart/', include('cart.urls')),
    path('payment/', include('payments.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, get_object_or_404
from .cart import Cart
from item.models import Item
from django.http import JsonResponse

# Create your views here.

def cartDetail(request):
    # Get the cart
    cart = Cart(request)
    cartItems = cart.getItems
    quantities = cart.getQuantities
    totals = cart.cartTotal()
    return render(request, 'cart/cartDetail.html', {"cartItems": cartItems, "quantities": quantities, "totals": totals})

def cartAdd(request):
    # Get the cart
    cart = Cart(request)
    # Test for POST
    if request.POST.get('action') == 'post':
        # Get stuff
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('product_qty'))
        
        # Lookup the item in the database
        item = get_object_or_404(Item, id=product_id)
        
        # Save the item to the cart (to the session)
        cart.add(item=item, quantity=product_qty)
        
        # Get cart quantity
        cartQuantity = cart.__len__()
        
        # Return a JSON response
        # response = JsonResponse({'Item name': item.name})
        response = JsonResponse({'Quantity': cartQuantity})
        return response
        

def cartDelete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        # Get stuff
        product_id = int(request.POST.get('product_id'))
        
        # Call delete method
        cart.cartDelete(item = product_id)
        
        response = JsonResponse({'item': 'product_id'})
        return response

def cartUpdate(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        # Get stuff
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('product_qty'))

        cart.cartUpdate(item = product_id, quantity = product_qty)
        
        response = JsonResponse({'qty': 'product_qty'})
        return response

cart/templates/cart/cartDetail.html
{% extends 'core/base.html' %}

{% block title %}Cart{% endblock %}

{% block content %}
    <div class="container-fluid p-4 bg-gray-100 rounded-xl text-center mt-5 mb-5">
        <h1 class="text-3xl font-bold text-pink-600">Shopping Cart</h1>

        <div class="container-fluid p-4 rounded-xl mt-5 mb-5 d-flex justify-content-center">
            <div class="d-flex flex-column align-items-center w-100">
                {% if cartItems %}
                    {% for item in cartItems %}
                        <div class="card mb-3" style="max-width: 1000px;">
                            <div class="row g-0">
                            <div class="col-md-4">
                                <img src="{{ item.image.url }}" class="img-fluid rounded-start" alt="{{ item.name }}">
                            </div>
                            <div class="col-md-8 d-flex align-items-center">
                                <div class="card-body">
                                <h5 class="card-title font-semibold text-xl">{{ item.name }}</h5>
                                <small class="card-text text-gray-400 mt-2 mb-2">{{ item.description }}</small><br>
                                <br><p class="card-text">Price: {{ item.price }}</p><br>
                                <div class="row justify-content-center">
                                    <div class="col-md-2">
                                    <p class="text-lg">Quantity:</p>
                                    </div>
                                    <div class="col-md-2">
                                        <select class="form-select" id="select{{ item.id }}">
                                            <option selected>
                                                {% for key, value in quantities.items %}
                                                    {% if key == item.id|slugify %}
                                                        {{ value }}
                                                    {% endif %}
                                                {% endfor %}
                                            </option>
                                            <option value="1">1</option>
                                            <option value="2">2</option>
                                            <option value="3">3</option>
                                            <option value="4">4</option>
                                            <option value="5">5</option>
                                        </select>
                                    </div>
                                    <div class="col-md-2">
                                        <button type="button" data-index="{{ item.id }}" class="btn text-lg font-semibold bg-pink-400 text-white rounded-xl hover:bg-pink-600 updateCart">Update</button>
                                    </div>
                                    <div class="col-md-1">
                                        <button type="button" data-index="{{ item.id }}" class="btn text-lg font-semibold bg-purple-400 text-white rounded-xl hover:bg-purple-600 deleteItem d-flex align-items-center justify-content-center">
                                            Delete
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash ml-1" viewBox="0 0 16 16">
                                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                                <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                                            </svg>
                                        </button>
                                    </div>
                            </div>
                                
                            </div>
                            </div>
                            </div>

                            
                        </div>
                    {% endfor %}
                    <p class="mt-3 mb-3 text-3xl">Total $ {{ totals }}</p>

                    <a href="{% url 'payments:payment' %}" class="btn text-lg font-semibold bg-pink-500 text-white rounded-xl hover:bg-pink-700 d-flex align-items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill mr-2" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
                          </svg>
                         Buy your dream wedding
                    </a>
                    
                {% else %}
                    <p class="text-lg"><em>Your cart is empty</em></p>
                    <br><br><br><br><br><br><br><br><br><br><br><br>
                {% endif %}
            </div>
          </div>




<script>
    // Update cart item quantity
    $(document).on('click', '.updateCart', function(e){
        e.preventDefault();
        // Grab the item id
        var itemId = $(this).data('index');
        var quantity = $('#select' + itemId + ' option:selected').text();

        $.ajax({
            type: 'POST',
            url: '{% url "cart:cartUpdate" %}',
            data:{
                product_id: itemId,
                product_qty: quantity,
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'
            },
            success: function(json){
                location.reload();
            },
            error: function(xhr, errmsg, err){}
        });
    })

    // Delete cart item
    $(document).on('click', '.deleteItem', function(e){
        e.preventDefault();

        $.ajax({
            type: 'POST',
            url: '{% url "cart:cartDelete" %}',
            data:{
                product_id: $(this).data('index'),
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'
            },
            success: function(json){
                location.reload();
            },
            error: function(xhr, errmsg, err){}
        });
    });
</script>

{% endblock %}