cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('detail/', views.cartDetail, name='cartDetail'),
    path('add/', views.cartAdd, name='cartAdd'),
    path('delete/', views.cartDelete, name='cartDelete'),
    path('update/', views.cartUpdate, name='cartUpdate'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('services/', views.services, name='services'),
    path('signup/', views.signup, name='signup'),
    path('signup/vendors/', views.signupVendors, name='signupVendors'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm), name='login'),
    path('profile/', views.profile, name='profile'),
    path('deleteAccount/', views.deleteAccount, name='deleteAccount'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),   
    path('<int:pk>/edit/', views.edit, name='edit'),   
]

weddingwizard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from django.contrib import admin
from django.urls import path, include

# Added by me

from core.views import index, services

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('cart/', include('cart.urls')),
    path('payment/', include('payments.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Custom User model
class CustomUser(AbstractUser):
    is_client = models.BooleanField(default=False)
    is_vendor = models.BooleanField(default=False)

# Profile model
class Profile(models.Model):
    USER_TYPE_CHOICES = (
        ('client', 'Client'),
        ('vendor', 'Vendor'),
    )
    
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    user_type = models.CharField(max_length=10, choices=USER_TYPE_CHOICES, default='client')
    
    # Client-specific fields
    partner1_name = models.CharField(max_length=100, blank=True, null=True)
    partner2_name = models.CharField(max_length=100, blank=True, null=True)
    birth_year1 = models.IntegerField(blank=True, null=True)
    birth_year2 = models.IntegerField(blank=True, null=True)

    # Vendor-specific fields
    vendor_name = models.CharField(max_length=100, blank=True, null=True)
    vendor_identifier = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.user.username

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from datetime import date
from .models import CustomUser, Profile

class SignupForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'w-full py-2 px-3 rounded-xl'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email',
                                                            'class': 'w-full py-2 px-3 rounded-xl'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                 'class': 'w-full py-2 px-3 rounded-xl'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm password',
                                                                 'class': 'w-full py-2 px-3 rounded-xl'}))
    partner1_name = forms.CharField(max_length=100, label="Your name",
                                    widget=forms.TextInput(attrs={'placeholder': 'Your name',
                                                                  'class': 'w-full py-2 px-3 rounded-xl'}))
    partner2_name = forms.CharField(max_length=100, label="Your partner's name",
                                    widget=forms.TextInput(attrs={'placeholder': 'Your partner\'s name',
                                                                  'class': 'w-full py-2 px-3 rounded-xl'}))
    birth_year1 = forms.IntegerField(label="Your birth year",
                                     widget=forms.NumberInput(attrs={'placeholder': 'Your birth year',
                                                                     'class': 'w-full py-2 px-3 rounded-xl'}))
    birth_year2 = forms.IntegerField(label="Your partner's birth year",
                                     widget=forms.NumberInput(attrs={'placeholder': 'Your partner\'s birth year',
                                                                     'class': 'w-full py-2 px-3 rounded-xl'}))
    
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2', 'partner1_name', 'partner2_name', 'birth_year1', 'birth_year2')
        
    def clean(self):
        cleaned_data = super().clean()
        birth_year1 = cleaned_data.get("birth_year1")
        birth_year2 = cleaned_data.get("birth_year2")

        if birth_year1 and birth_year2:
            current_year = date.today().year
            age1 = current_year - birth_year1
            age2 = current_year - birth_year2

            if age1 < 18 or age2 < 18:
                self.add_error('birth_year1', "The partners must be at least 18 years old.")
                self.add_error('birth_year2', "The partners must be at least 18 years old.")
                
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_client = True
        
        if commit:
            user.save()
            profile = Profile.objects.create(
                user=user,
                user_type='client',
                partner1_name=self.cleaned_data['partner1_name'],
                partner2_name=self.cleaned_data['partner2_name'],
                birth_year1=self.cleaned_data['birth_year1'],
                birth_year2=self.cleaned_data['birth_year2']
            )
        return user

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'w-full py-2 px-3 rounded-xl'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                 'class': 'w-full py-2 px-3 rounded-xl'}))

class SignupVendorsForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'w-full py-2 px-3 rounded-xl'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email',
                                                            'class': 'w-full py-2 px-3 rounded-xl'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                 'class': 'w-full py-2 px-3 rounded-xl'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm password',
                                                                 'class': 'w-full py-2 px-3 rounded-xl'}))
    name = forms.CharField(max_length=100, label="Vendor's name",
                           widget=forms.TextInput(attrs={'placeholder': 'Vendor\'s name',
                                                         'class': 'w-full py-2 px-3 rounded-xl'}))
    id = forms.IntegerField(label="Vendor's ID",
                            widget=forms.NumberInput(attrs={'placeholder': 'Vendor\'s ID',
                                                            'class': 'w-full py-2 px-3 rounded-xl'}))
    
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2', 'name', 'id')
        
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_vendor = True
        
        if commit:
            user.save()
            profile = Profile.objects.create(
                user=user,
                user_type='vendor',
                vendor_name=self.cleaned_data['name'],
                vendor_identifier=self.cleaned_data['id']
            )
        return user

class EmailUpdateForm(forms.ModelForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'placeholder': 'Update your email address',
                                                            'class': 'form-control w-full py-2 px-3 rounded-xl'}))

    class Meta:
        model = User
        fields = ['email']

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from item.models import Category, Item
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import SignupForm, SignupVendorsForm, EmailUpdateForm

# Create your views here.

def index(request):
    return render(request, 'core/index.html')

def services(request):
    items = Item.objects.filter(is_available=True)[0:30]
    categories = Category.objects.all()
    
    return render(request, 'core/services.html', {
        'categories': categories,
        'items': items,  
    })
    
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            return redirect('/login/')
    else:
        form = SignupForm()
    
    return render(request, 'core/signup.html', {
        'form': form,
    })
    
def signupVendors(request):
    if request.method == 'POST':
        form = SignupVendorsForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            return redirect('/login/')
    else:
        form = SignupVendorsForm()
        
    return render(request, 'core/signupVendors.html', {
        'form': form,
    })

@login_required
def profile(request):
    profile = request.user.profile 
    if request.method == 'POST':
        form = EmailUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('/')  # Redirigir al inicio tras actualizar
    else:
        form = EmailUpdateForm(instance=request.user)

    return render(request, 'core/profile.html', {'form': form, 'profile': profile})

@login_required
def deleteAccount(request):
    if request.method == 'POST':
        user = request.user
        user.delete()
        logout(request)
        messages.success(request, 'Your account has been deleted!')
        return redirect('/')
    return render(request, 'core/deleteAccount.html')

core/templates/core/base.html
<!doctype html>
<html lang="es-co">

<!-- HEAD -->
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {% block title %} {% endblock %} | WeddingWizard</title>
    
    <!-- FAVICON -->
    <link rel="icon"  href="{% static 'img/WeddingWizardCon.png' %}" type="image/png">
    <!-- END FAVICON -->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

    <style>
        
        .google-translate {
            display: grid;
            background-color: #ffffff;
            border-radius: 5px;
            height: 10px;
            width: 70px;
            
            
        }
        
        /* Estilo para ocultar el encabezado del widget de Google Translate */
        iframe.VIpgJd-ZVi9od-ORHb-OEVmcd.skiptranslate {
        display: none !important;
        }

        .skiptranslate.goog-te-gadget-container {
            display: none;
        }

        /* Estilos personalizados para el widget de Google Translate */
        .skiptranslate.goog-te-gadget {
            weight: auto;
            height: auto;
            /* Establecer un fondo y color de texto */
            background-color: #ffffff;
            color: #333;
            /* Ajustar el padding y margen */
            padding: 10px;
            margin-bottom: 10px;
            /* Establecer un borde y redondear las esquinas */
            border: 1px solid #ccc;
            border-radius: 5px;
            /* Alinear el texto al centro */
            text-align: center;
        }

        /* Estilos para el enlace "Traductor de Google" */
        .skiptranslate.goog-te-gadget a {
            /* Cambiar el color y subrayar al pasar el ratón */
            color: #4285f4;
            text-decoration: none;
        }

        .skiptranslate.goog-te-gadget a:hover {
            text-decoration: underline;
        }
        
        /* Ocultar el logo de Google Translate */
        .skiptranslate.goog-te-gadget img {
            display: none;
        }

        

        /* Estilo para el selector de idioma */
        .goog-te-combo {
            /* Cambiar el fondo y el color de texto */
            background-color: #ffffff;
            color: #333333;
            /* Ajustar el padding y margen */
            padding: 8px 12px;
            margin: 0;
            /* Establecer un borde y redondear las esquinas */
            border: 1px solid #cccccc;
            border-radius: 4px;
            /* Establecer el tamaño de la fuente y hacer que sea más legible */
            font-size: 14px;
            font-weight: normal;
            /* Hacer que el cursor sea un puntero al pasar el ratón */
            cursor: pointer;
            /* Establecer una apariencia más amigable al usuario */
            appearance: none;
        }

        /* Estilo para el hover del selector de idioma */
        .goog-te-combo:hover {
            
            /* Cambiar el color de fondo al pasar el ratón */
            background-color: #f0f0f0;
        }

        /* Estilo para el foco del selector de idioma */
        .goog-te-combo:focus {
            /* Cambiar el color de borde al obtener el foco */
            border-color: #007bff;
            /* Añadir un efecto de sombra al obtener el foco */
            box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
        }


    </style>
    

</head>
<!-- END HEAD -->

<body>
 
<!-- NAVBAR -->
<nav class="py-4 px-4 flex justify-between items-center border-b bg-gray-100 border-gray-100">
    <a href="/" class="navbar-brand">
        <img src="{% static 'img/WeddingWizard.png' %}" alt="WeddingWizard" width="60" height="60">
    </a>

    <div class="d-flex flex-column flex-md-row align-items-center">
        <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500 d-flex align-items-center mx-2">
            <span class="mr-2">Browse</span>
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-search-heart" viewBox="0 0 16 16">
                <path d="M6.5 4.482c1.664-1.673 5.825 1.254 0 5.018-5.825-3.764-1.664-6.69 0-5.018"/>
                <path d="M13 6.5a6.47 6.47 0 0 1-1.258 3.844q.06.044.115.098l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1-.1-.115h.002A6.5 6.5 0 1 1 13 6.5M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11"/>
              </svg>
        </a>

        <div class="d-flex justify-content-md-between align-items-center mx-md-2 mx-2 ml-3">
        {% if user.is_authenticated %}
            {% if user.profile.user_type == 'vendor' %}
                <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500 d-flex align-items-center">
                    <span class="mr-2">New item</span>
                </a>

                <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-pink-400 text-white rounded-xl hover:bg-pink-600 mx-2">Dashboard</a>
            
                {% else %}
                <a href="{% url 'cart:cartDetail' %}" class="btn bg-pink-400 px-6 py-3 text-lg text-white font-semibold rounded-xl mx-2 hover:bg-pink-600 d-flex align-items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-bag-heart me-2" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M10.5 3.5a2.5 2.5 0 0 0-5 0V4h5zm1 0V4H15v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4h3.5v-.5a3.5 3.5 0 1 1 7 0M14 14V5H2v9a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1M8 7.993c1.664-1.711 5.825 1.283 0 5.132-5.825-3.85-1.664-6.843 0-5.132"/>
                    </svg>
                    <span>Cart</span>
                    <span class="badge bg-white text-pink-400 ms-2 rounded-pill" id="cartQuantity">{{ cart|length }}</span>
                </a>


                    <a href="{% url 'core:profile' %}" class="px-6 py-3 text-lg font-semibold bg-pink-400 text-white rounded-xl hover:bg-pink-600 mx-2">Profile</a>
                {% endif %}
                
            <!-- LOGOUT -->
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="px-6 py-3 text-lg font-semibold bg-pink-300 text-white rounded-xl hover:bg-pink-600 mx-2">Log Out</button>
            </form>
            <!-- END LOGOUT -->
        </div>

        {% else %}
        <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-pink-500 text-white rounded-xl hover:bg-pink-700 mx-2">Sign up</a>
        <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-pink-500 text-white rounded-xl hover:bg-pink-700 mx-2">Log in</a>
        {% endif %}
    </div>
</nav>
<!-- END NAVBAR -->






<!-- PAGE'S CONTENT -->
<div class="fluid-container">
    {% block content %}
    {% endblock %}
</div>
<!-- END PAGE'S CONTENT -->




<!-- FOOTER -->
<footer class="py-6 px-6 flex justify-between bg-pink-100">
    <div class="w-2/3 pr-10" >
        <h3 class="mb-5 font-semibold text-pink-700 text-xl">About us</h3>
        <p class="text-lg text-pink-700">At WeddingWizard, we simplify wedding planning with our all-in-one online service. No meetings, no stress—just add your desired products to your cart, and we’ll take care of the rest. Enjoy a seamless experience and a perfect wedding day with WeddingWizard.</p>
    </div>

    <div class="w-1/3">
        <h3 class="mb-5 font-semibold text-pink-700">Menu</h3>
        <ul class="space-y-2">
            <li><a href="/" class="text-lg text-pink-700 hover:text-pink-400">Home</a></li>
            <li><a href="{% url 'core:services' %}" class="text-lg text-pink-700 hover:text-pink-400">Services</a></li>

            {% if not user.is_authenticated %}
            <li><a href="{% url 'core:signupVendors' %}" class="text-lg text-pink-700 hover:text-pink-500">Work with us</a></li>
            {% endif %}


        </ul>
    </div>
</div>
</footer>
<!-- END FOOTER -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>


<!-- GOOGLE TRANSLATE -->

    <script type="text/javascript">
        function googleTranslateElementInit() {
	        new google.translate.TranslateElement({pageLanguage: 'en', includedLanguages: 'es,en,fr,it', layout: google.translate.TranslateElement.InlineLayout.VERTICAL, gaTrack: true}, 'google_translate_element');
        }
    </script>
    
    

    <script type="text/javascript" src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

<!-- END GOOGLE TRANSLATE -->

  </body>
</html>

core/templates/core/deleteAccount.html
{% extends 'core/base.html' %}

{% block title %}Delete Account{% endblock %}

{% block content %}

<div class="container-fluid mt-6 px-6 py-12 bg-pink-50 rounded-xl mb-12 mr-5 ml-5">
    <h2 class="text-lg mb-6 text-bold">Are you sure you want to delete your account?</h2>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-800 ml-2">Confirm Delete</button>

        <a href="{% url 'core:profile' %}" class="px-6 py-3 text-xl font-semibold bg-green-400 text-white rounded-xl hover:bg-green-600 ml-2">Cancel</a>
    </form>
</div>



{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log In{% endblock %}

{% block content %}
    <div class="w-1/2 my-3 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl  text-center">Log In</h1>

        <form method="post" action="{% url 'core:login'%}">
            {% csrf_token %}

            <div class="my-6 mx-auto text-xl">
                <label class="block mb-2">Username</label>
                {{ form.username }}
                {% for error in form.username.errors %}
                    <p class="text-red-500">{{ error }}</p>
                {% endfor %}
            </div>

            <div class="my-6 mx-auto text-xl">
                <label class="block mb-2">Password</label>
                {{ form.password }}
                {% for error in form.password.errors %}
                    <p class="text-red-500">{{ error }}</p>
                {% endfor %}
            </div>

            {% if form.non_field_errors %}
                <div class="mb-6 p-6 mx-auto bg-red-100 rounded-xl">
                    {% for error in form.non_field_errors %}
                        <p class="text-red-500">{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}

            <button type="submit" class="block mx-auto p-2 bg-pink-500 hover:bg-pink-700 text-white font-bold rounded">Log In</button>
        </form>
    </div>   
    
    <p>{{ message }}</p>
{% endblock %}

core/templates/core/profile.html
{% extends 'core/base.html' %}
{% block title %}Profile{% endblock %}

{% block content %}

<div class="container-fluid mt-6 px-6 py-12 bg-pink-50 rounded-xl mb-12 mr-5 ml-5">
    <h1 class="mb-12 text-4xl text-center text-bold text-pink-600 ">Edit profile</h1>

    <h3 class="mb-12 text-2xl text-semibold">Hello {{ profile.partner1_name }} and {{ profile.partner2_name }}!</h3>

    <div class="container-fluid">
        <div class="row">
          <div class="col-6">
            <div class="container-fluid">
                <p class="mb-4 text-lg">Your current email is: {{ user.email }}</p>
                <form method="post">
                    {% csrf_token %}
                    <div class="fluid-container mb-4">
                        <div class="flex items-center">
                            <label for="email" class="form-label mr-2 text-lg">New email:</label>
                            <input type="email" name="email" value="{{ user.email }}" class="form-control w-80 mr-2" id="email">
                            <button type="submit" class="px-6 py-3 text-lg font-semibold bg-pink-400 text-white rounded-xl hover:bg-pink-600 ml-2">Update Email</button>
                        </div>
                    </div>
                </div>
            </form>
          </div>

          <div class="col-6">
            <div class="fluid-container bg-white rounded-xl w-100 text-center" style="display: flex; flex-direction: column; align-items: center;">
                <h2 class="text-lg text-pink-500 font-semibold p-2">Change Language</h2>
                <div id="google_translate_element" class="google-translate" style= "weight: 100px; height: 100px;margin-bottom: 30px; display: flex; justify-content: center; align-items: center;"></div>
            </div>
          </div>
        </div>
      </div>

      <div class="container-fluid p-3">
        <h2 class="text-lg font-bold">Delete Account</h2>
        </br>
        <p class="mb-4">If you want to delete your account, click the button below.</p>
        </br>
        <a href="{% url 'core:deleteAccount' %}" class="mt-4 mb-4 px-6 py-3 text-lg font-semibold bg-pink-400 text-white rounded-xl hover:bg-pink-600">Delete My Account</a>
      </div>
</div>
{% endblock %}

core/templates/core/services.html
{% extends 'core/base.html'%}
{% block title %}Services{% endblock %}


{% block content %}
    <div class="fluid-container mt-6 mb-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h1 class="mb-12 text-2xl text-center text-bold">Newest Items</h1>

        <div class="col-span-3">
            <div class="fluid-container grid grid-cols-5 gap-3 mt-4 mr-4">
                {% for item in items %}
                    <div>
                        <a href=" {% url 'item:detail' item.id %}">
                            <div>
                                <img src="{{ item.image.url }}" class="rounded-t-xl">
                            </div>
    
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ item.name }}</h2>
                                <p class="text-gray-500">Price: {{ item.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="container-fluid text-center mt-5 mt-lg-6 p-3">
        <div class="row align-items-center" style="min-height: 25vh;">
    
        <div class="col-sm-6 d-flex justify-content-end align-items-center">
            <h1 class="text-4xl font-semibold text-pink-600"data-section="landing_services" data-value="s-text-1">Find more options!</h1>
        </div>
    
        <div class="col-sm-6 d-flex justify-content-start align-items-center">
            <a href="{% url 'item:items' %}" class="px-6 py-3 text-lg font-semibold bg-pink-400 text-white rounded-xl hover:bg-pink-600">
            <span data-section="landing_services" data-value="s-text-2">Browse</span>
            </a>
        </div>
        </div>
    </div>

	<div class="fluid-container mt-6 mb-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h1 class="mb-12 text-2xl text-center text-bold">Categories</h1>

        <div class="fluid-container grid grid-cols-5 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    <div class="w-1/2 my-3 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl text-center">Sign Up</h1>

        <form method="post" action=".">
            {% csrf_token %}
            
            <div class="my-6 mx-auto text-xl">
                <label class="block mb-2 text-xl">Username</label>
                {{ form.username }}
            </div>

            <div class="my-6 mx-auto text-xl">
                <label class="block mb-2">Email</label>
                {{ form.email }}
            </div>

            <div class="row my-6">
                <div class="col-md-6 form-group text-xl">
                    <label class="block mb-2">Password</label>
                    {{ form.password1 }}
                </div>
                <div class="col-md-6 form-group text-xl">
                    <label class="block mb-2">Confirm password</label>
                    {{ form.password2 }}
                </div>
            </div>

            <div class="row my-6">
                <div class="col-md-6 form-group text-xl">
                    <label class="block mb-2">Your name</label>
                    {{ form.partner1_name }}
                </div>
                <div class="col-md-6 form-group text-xl">
                    <label class="block mb-2">Your partner's name</label>
                    {{ form.partner2_name }}
                </div>
            </div>

            <div class="row my-6">
                <div class="col-md-6 form-group text-xl">
                    <label class="block mb-2">Your birth year</label>
                    {{ form.birth_year1 }}
                </div>
                <div class="col-md-6 form-group text-xl">
                    <label class="block mb-2">Your partner's birth year</label>
                    {{ form.birth_year2 }}
                </div>
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-6 p-6 mx-auto bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button type="submit" class="block mx-auto p-2 bg-pink-500 hover:bg-pink-700 text-white font-bold rounded">Sign Up</button>
        </form>
    </div>   
    
    <p>{{ message }}</p>
{% endblock %}