cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('detail/', views.cartDetail, name='cartDetail'),
    path('add/', views.cartAdd, name='cartAdd'),
    path('delete/', views.cartDelete, name='cartDelete'),
    path('update/', views.cartUpdate, name='cartUpdate'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),   
    path('<int:pk>/edit/', views.edit, name='edit'),   
]

weddingwizard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from django.contrib import admin
from django.urls import path, include

# Added by me

from core.views import index, services

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('cart/', include('cart.urls')),
    path('payment/', include('payments.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.db import models
from django.conf import settings

class Category(models.Model):
    name = models.CharField(max_length=255)
    
    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='items_images', blank=True, null=True)
    offered_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='items', on_delete=models.CASCADE)
    is_available = models.BooleanField(default=True)
    
    def __str__(self):
        return self.name

item/forms.py
from django import forms

from .models import Item

INPUT_CLASSES = 'w-full py-2 px-3 rounded-xl'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image',)
        
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
                }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
                }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
                }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
                }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
                }),
        }
        
class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image', 'is_available')
        
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
                }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
                }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
                }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
                }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
                }),
        }

item/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

from .forms import NewItemForm, EditItemForm
from .models import Category, Item

# Create your views here.

def items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_available=True)
    
    if category_id:
        items = items.filter(category_id=category_id)
    
    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))
    
    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
    })

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_available=True).exclude(pk=pk)[0:3]
    
    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })
    
@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        
        if form.is_valid():
            item = form.save(commit=False)
            item.offered_by = request.user
            item.save()
            
            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()
    
    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New Item',
    })
    
@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, offered_by=request.user)
    item.delete()
    
    return redirect('dashboard:index')

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, offered_by=request.user)
    
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)
        
        if form.is_valid():
            form.save()
            
            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)
    
    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit Item',
    })

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6 p-5">
    <div class="col-span-2">
        <img src="{{ item.image.url }}" class="rounded-xl">
    </div>

    <div class="col-span-3 bg-gray-100 rounded-xl p-5">
        <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
        <p class="mb-6 text-lg"><strong>Price:</strong> ${{ item.price }}</p>
        <p class="mb-6 text-m"><strong>Seller:</strong> {{ item.offered_by }}</p>

        {% if item.description %}
            <p class="text-gray-700">
                <strong class="">Description:</strong><br>
                {{ item.description }}</p>
        {% endif %}

        {% if request.user == item.offered_by %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>You're the seller of this item</p>

                <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-purple-400 text-white rounded-xl">Edit</a>
                <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-pink-500 text-white rounded-xl">Delete</a>
            </div>
        {% else %}
        
            <br>
            <div class="row">
                <div class="col-md-2">
                <p class="text-lg">Quantity:</p>
                </div>
                <div class="col-md-2">
                    <select class="form-select" id="qtyCart">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                    </select>
                </div>
            </div>
            

            <button type="button" value="{{ item.id }}" class="inline-block px-6 py-3 mt-6 text-lg font-semibold bg-pink-500 text-white rounded-xl hover:bg-pink-700" id="addCart">Add to Cart</button>

        {% endif %}
    </div>
</div>

<div class="fluid-container mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h1 class="mb-12 text-2xl text-center text-bold">Related Items</h1>

    <div class="fluid-container grid grid-cols-5 gap-3">
        {% for item in related_items %}
            <div>
                <a href=" {% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>

    <script>
        // Check if the button is clicked
        $(document).on('click', '#addCart', function(e){
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url "cart:cartAdd" %}',
                data:{
                    product_id: $(addCart).val(), 
                    product_qty: $('#qtyCart option:selected').text(),
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    action: 'post'
                },
                success: function(json){
                    //console.log(json)
                    document.getElementById("cartQuantity").textContent = json.Quantity
                },
                error: function(xhr, errmsg, err){}
            });
        });
    </script>

{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1 class = "mb-6 text-3xl text-center text-pink-700 p-6 text-bold">{{ title }}</h1>

    <form method = "post" action = "." enctype = "multipart/form-data">
        {% csrf_token %}

        <div class = "fluid-container bg-pink-100 p-3 ml-3 mr-3 rounded-xl">
            {{ form.as_p }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-6 p-6 mx-auto bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="block mt-2 mb-2 mx-auto p-3 bg-pink-500 hover:bg-pink-700 text-white font-bold rounded">Submit</button>
    </form>

{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title %}Items{% endblock %}

{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4 ">
        <div class="col-span-1 mt-4 ml-4 bg-gray-100 rounded-xl p-4">
            <form method="get" action="{% url 'item:items'%}">
                <div class="fluid-container">
                    <input name="query" class="w-2/3 py-2 px-8 border text-lg rounded-xl" type="text" value="{{ query }}" placeholder="Search">
                    <button class="mt-2 py-2 px-8 text-lg bg-pink-500 text-white rounded-xl">Search</button>
                </div>
            </form>

            <hr class="my-6">
            <p class="text-lg font-semibold">Categories</p>
            <ul>
                {% for category in categories%}
                    <li class="py-2 px-2 rounded-xl" {% if category.id == category_id %} bg-gray-200 {% endif %}>
                        <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </li>  
                {% endfor %}
            </ul>

            <ul>
                <li class="py-2 px-2 rounded-xl">
                    <a href="{% url 'item:items' %}" class="mt-2 p-2 px-83 bg-pink-500 text-white rounded-xl">Clear filters</a>
                </li>
            </ul>
        </div>

        <div class="col-span-3">
            <div class="fluid-container grid grid-cols-5 gap-3 mt-4 mr-4">
                {% for item in items %}
                    <div>
                        <a href=" {% url 'item:detail' item.id %}">
                            <div>
                                <img src="{{ item.image.url }}" class="rounded-t-xl">
                            </div>
    
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ item.name }}</h2>
                                <p class="text-gray-500">Price: {{ item.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}